Add pointsCount method
AndreyMukhametzyanov/BlackJack pull request #1
Opened 2021-03-20 09:18 UTC by AndreyMukhametzyanov

2021-03-20 09:19 UTC, GolovkoStepan requested changes

2021-03-20 09:19 UTC, GolovkoStepan commented on src/com/game/Card.java
> +
А где решение?

2021-03-20 09:20 UTC, AndreyMukhametzyanov commented on src/com/game/Card.java
> +
пока нету

2021-03-20 13:13 UTC, GolovkoStepan requested changes
Надо удалить из репозитория сборку проекта, а именно out/production/BlackJack
В репозитории должны быть только файлы кода.

git rm out/

Добавить в .gitignore папку  out/ чтобы она больше не попала случайно в коммит.

2021-03-24 04:22 UTC, GolovkoStepan requested changes

2021-03-24 04:22 UTC, GolovkoStepan commented on .gitignore
> +.out
А что это у тебя за папка .out? Разве такая есть? 
Есть папка .idea с настройками среды разработки, но папки .out нету же

исправь на /out

2021-03-24 04:22 UTC, GolovkoStepan commented on .gitignore
> +.out
out/production/BlackJack/com/game/Card.class
out/production/BlackJack/com/game/Main.class

это файлы скомпилированного проекта, их не должно быть в репозитории - надо удалить

2021-03-24 04:22 UTC, GolovkoStepan commented on src/com/game/Card.java
> +    } // получение конкретной карты
коммент звучит как-то не оч, карта в этом контексте это класс card
тут скорее надо написать что-то типа: получение номера карты

2021-03-24 04:22 UTC, GolovkoStepan commented on src/com/game/Card.java
> +    public static Integer pointsCount (ArrayList<Card> cards) { // метод для подсчета очков
сигнатура метода норм.
метод принимает массив с картами, 1 2 или 3 шутки
мы идем по массиву и для каждой карты суммируем ее цену в какую нить переменную

ну и потом просто возвращаем эту сумму

2021-03-24 04:22 UTC, GolovkoStepan commented on src/com/game/Card.java
> +            if (hand.size()==1){  sum = sum + Card.rankOfCard(elem);}
Зачем нужна эта проверка на размер массива?

2021-03-24 04:22 UTC, GolovkoStepan commented on src/com/game/Card.java
> +        return sum;
Нужно учитывать то, что в массиве может быть туз
Когда туз есть,  если мы вышли за 21, то надо вычесть 10

2021-03-25 17:39 UTC, GolovkoStepan commented on src/com/game/Card.java
> +        for (int i = 0; i < cards.size(); i++) {
А тут можно же использовать foreach? for(Card card in cards) как то так вроде
Не будет возни с индексами

2021-03-25 17:41 UTC, GolovkoStepan commented on src/com/game/Card.java
> +            for (int j = 0; j < cards.size() ; j++) {
оу, это лишний цикл. Можно искать туз в цикле, где мы считаем очки
Если туз есть например, то какую нить boolean переменную ставим в true

после цикла ее проверяем

2021-03-25 17:42 UTC, GolovkoStepan commented on src/com/game/Card.java
> +    public static Integer pointsCount(ArrayList<Card> cards) { // метод для подсчета очков
Решение в принципе рабочее, но вот вопрос на миллион: А что, если у нас будет 2 туза на руках? Или даже три)

2021-03-27 08:06 UTC, GolovkoStepan approved these changes

2021-03-27 08:07 UTC, merged