CardTest
AndreyMukhametzyanov/BlackJack pull request #2
Opened 2021-03-30 18:17 UTC by AndreyMukhametzyanov

2021-03-31 06:54 UTC, GolovkoStepan requested changes

2021-03-31 06:54 UTC, GolovkoStepan commented on src/main/java/com/game/Card.java
> +        return String.format("[##]", numberOfCard, suit);
Зачем использовать интерполяцию строк тут? Можно просто return "[##]"

2021-03-31 06:54 UTC, GolovkoStepan commented on src/test/java/com/game/CardTest.java
> +        String[] numbersOfCardTest = {"2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A"}; // номер карты B
Это же есть в классе card, можно оттуда взять. Тока надо будет сделать паблик.
По сути, это константы - их можно не приватить.

2021-03-31 06:55 UTC, GolovkoStepan commented
target/classes/com/game/Main.class

В коммит опять попали какая-то бинарщина после компиляции. Надо выпилить

2021-03-31 06:59 UTC, GolovkoStepan commented
2 коммита с одинаковым сообщением не оч красиво смотрится

Попробуй объединить комиты в один

git rebase -i HEAD~2

для нужного комита изменить pick на s

удалить коммит msg 

git push -f

2021-04-03 13:41 UTC, AndreyMukhametzyanov commented on src/main/java/com/game/Card.java
> +        return String.format("[##]", numberOfCard, suit);
А этот метод не должен тоже как бы сохранять в себе карты? Просто их не отображать?

2021-04-03 13:50 UTC, AndreyMukhametzyanov commented
> target/classes/com/game/Main.class
> 
> В коммит опять попала какая-то бинарщина после компиляции. Надо выпилить

2021-04-04 08:01 UTC, GolovkoStepan commented on src/main/java/com/game/Card.java
> +        return String.format("[##]", numberOfCard, suit);
ну вот мы хотим как то вывести карту на экран, для лицевой стороны у нас метод showCard - ему надо знать масть и номер чтобы ее вывести. Тут все ок. А чтобы ее перевернутую вывести нам ничего знать не надо, тк у всех карт одинаковая задняя сторона. Поэтому можно просто вернуть return "[##]

Тем более, ты используешь интерполяцию, передаешь туда какие то значения, чтобы они подставлялись в строку, а сами маркеры подстановки не указываешь. Какой смысл тогда это использовать?

2021-04-04 08:02 UTC, GolovkoStepan commented on src/test/java/com/game/CardTest.java
> +        String[] numbersOfCardTest = {"2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A"}; // номер карты B
не, оставь как есть, сохраним скрытие реализации

2021-04-04 08:13 UTC, GolovkoStepan requested changes

2021-04-04 08:13 UTC, GolovkoStepan commented on src/test/java/com/game/CardTest.java
> +    public void shuffleTest() { // Как сделать тест если метод всегда мешает рандомно?
по сути этот метод - обертка над стандартным методом shuffle, тестировать его работу не имеет смысла

но для успокоения души, что называется, можно проверить, что он возвращает массив такого же размера, как и входной, но в другом порядке. Те размеры должны быть равны, но сами массивы не должны быть равны

2021-04-04 08:13 UTC, GolovkoStepan commented on src/test/java/com/game/CardTest.java
> +    public void pullOutCardsTest() { // не проходит проверки выводит java.lang.AssertionError: Expected :[[2♠], [3♠], [4♠]]  Actual   :[[2♠], [3♠], [4♠]]
идет сравнение объектов по идее, надо переопределить метод equals попробовать
https://www.geeksforgeeks.org/overriding-equals-method-in-java/

те чтобы сравнить 2 карты нам надо сравнить их масти и номера

2021-04-04 08:13 UTC, GolovkoStepan commented on src/test/java/com/game/CardTest.java
> +
удалить пустую строку

2021-04-04 08:13 UTC, GolovkoStepan commented on src/test/java/com/game/CardTest.java
> +
удалить пустую строку

2021-04-04 08:15 UTC, GolovkoStepan commented
давай попробуем прикрутить github actions
https://github.com/mikepenz/action-junit-report

чтобы можно было прям тут смотреть проходят тесты или нет

2021-04-10 08:18 UTC, GolovkoStepan approved these changes

2021-04-10 08:18 UTC, merged